
from dotenv import load_dotenv
load_dotenv()

from openai import AzureOpenAI
import os

client = AzureOpenAI(
    api_key=os.getenv("AZURE_OPENAI_API_KEY"),
    api_version="2024-02-15-preview",
    azure_endpoint=os.getenv("AZURE_OPENAI_ENDPOINT")
)


LLM_DISCLAIMER = (
    "\n\n---\n"
    "This explanation was generated by an AI system and may be incomplete or incorrect.\n\n"
)


SYSTEM_PROMPT = """
You are a housing assisstant explain the situation qualitatively.
Do not generate or estimate numerical prices, costs, percentages, or forecasts.
If the answer is uncertain, say so clearly.
"""

def call_llm(question: str) -> str:
    response = client.chat.completions.create(
        model=os.getenv("AZURE_OPENAI_DEPLOYMENT_NAME"),
        messages=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": question}
        ],
        temperature=0.2,
    )
    return LLM_DISCLAIMER + response.choices[0].message.content
