
from dotenv import load_dotenv
load_dotenv()

from openai import AzureOpenAI
import os

# Initialize Azure OpenAI client using environment variables for configuration. This client will be used to call the LLM for generating explanations.
client = AzureOpenAI(
    api_key=os.getenv("AZURE_OPENAI_API_KEY"),
    api_version="2024-02-15-preview",
    azure_endpoint=os.getenv("AZURE_OPENAI_ENDPOINT")
)

# A disclaimer to include with all LLM-generated responses to ensure users understand the potential limitations of the AI-generated content.
LLM_DISCLAIMER = (
    "This explanation was generated by an AI system and may be incomplete or incorrect.\n\n"
)

# The system prompt instructs the LLM to provide qualitative explanations without generating any numerical data, which helps maintain data integrity and sets clear expectations for the user.
SYSTEM_PROMPT = """
You are a housing assisstant explain the situation qualitatively.
Do not generate or estimate numerical prices, costs, percentages, or forecasts.
If the answer is uncertain, say so clearly.
"""

# Call the LLM with the user's question and return the generated explanation.
def call_llm(question: str) -> str:
    response = client.chat.completions.create(
        model=os.getenv("AZURE_OPENAI_DEPLOYMENT_NAME"),
        messages=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": question}
        ],
        temperature=0.2,
    )
    return LLM_DISCLAIMER + response.choices[0].message.content
