name: housing-signals-inference
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
      - azureml-inference-server-http
      - joblib
      - numpy
      - pandas
      - pyarrow
      - scikit-learn
